### ISSUE TITLE
Required options in units schema

### ISSUE THREAD

**Issue by Smeds** [hydra-genetics/snv_indels#61]
Should this section be updated or only have what is needed for this module?I guess lane isn't required by the module?

https://github.com/hydra-genetics/snv_indels/blob/795d70acf73722745f2a9133ef89a20ffa89f4c4/workflow/schemas/units.schema.yaml#L35-L39

**Comment by marrip** [comment]
I will add `barcode` as well and keep the stanzas required for indexing `units.tsv`
